from datetime import timezone

TARGET_TIMEZONE = timezone.utc
SESSION_GAP_SECONDS = 1800
ANOMALY_WINDOW_SECONDS = 300
BASELINE_WINDOW_COUNT = 12
ERROR_SPIKE_SIGMA = 2.0
SLOW_REQUEST_P95_FACTOR = 2.0
LOGIN_FAILURE_THRESHOLD = 5
SCAN_404_THRESHOLD = 10
RESOURCE_ANOMALY_SIGMA = 2.5
